-- Orders and invoices keep an immutable USD price / rate / SDG snapshot.
-- Later price or rate changes must not affect existing orders or invoices.
begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;

select plan(24);

-- Fixture customer, created the way the server does after OTP.
insert into auth.users (id, instance_id, aud, role, email, phone, phone_confirmed_at,
                        raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('10000000-0000-4000-8000-000000000001', '00000000-0000-0000-0000-000000000000',
        'authenticated', 'authenticated', 'snap@test.local', '249911000001', now(),
        '{"signup_verified":"otp"}', '{"full_name":"Snapshot Customer"}', now(), now());

update app_settings set usd_sdg_rate = 2600, kyc_threshold_usd = 100 where id;
update product_variants set price_usd = 1.10 where id = '00000000-0000-4000-c000-000000000001';

-- 1. Caller-supplied money values are ignored; the DB derives them.
insert into orders (id, user_id, variant_id, quantity, idempotency_key,
                    unit_price_usd, total_usd, usd_sdg_rate, total_sdg, status, kyc_required, reference, fulfillment_data)
values ('20000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001',
        '00000000-0000-4000-c000-000000000001', 3, gen_random_uuid(),
        0.01, 0.03, 1, 1, 'completed', false, 'FD-0000000', '{"player_id":"123456"}');

select is((select unit_price_usd from orders where id = '20000000-0000-4000-8000-000000000001'),
          1.10::numeric, 'tampered unit price replaced by the catalog price');
select is((select total_usd from orders where id = '20000000-0000-4000-8000-000000000001'),
          3.30::numeric, 'total_usd = price x quantity');
select is((select usd_sdg_rate from orders where id = '20000000-0000-4000-8000-000000000001'),
          2600::numeric, 'rate snapshot taken from settings, not the caller');
select is((select total_sdg from orders where id = '20000000-0000-4000-8000-000000000001'),
          8580::numeric, 'total_sdg = ceil(3.30 x 2600) = 8580');
select is((select status from orders where id = '20000000-0000-4000-8000-000000000001'),
          'new', 'caller cannot create an order in another status');
select ok((select reference ~ '^FD-[0-9]{7}$' and reference <> 'FD-0000000'
             from orders where id = '20000000-0000-4000-8000-000000000001'),
          'reference generated by the DB (FD- + 7 digits)');

-- Rounding rule: always up to whole SDG.
update app_settings set usd_sdg_rate = 2600.3333 where id;
insert into orders (id, user_id, variant_id, quantity, idempotency_key, fulfillment_data)
values ('20000000-0000-4000-8000-000000000002', '10000000-0000-4000-8000-000000000001',
        '00000000-0000-4000-c000-000000000001', 1, gen_random_uuid(), '{"player_id":"123456"}');
select is((select total_sdg from orders where id = '20000000-0000-4000-8000-000000000002'),
          2861::numeric, 'SDG rounded up: ceil(1.10 x 2600.3333 = 2860.37) = 2861');

-- 2. Change price and rate AFTER the order exists.
update product_variants set price_usd = 5.00 where id = '00000000-0000-4000-c000-000000000001';
update app_settings set usd_sdg_rate = 3000 where id;

select results_eq(
  $$ select unit_price_usd, total_usd, usd_sdg_rate, total_sdg from orders
      where id = '20000000-0000-4000-8000-000000000001' $$,
  $$ values (1.10::numeric, 3.30::numeric, 2600::numeric, 8580::numeric) $$,
  'existing order unchanged after price 1.10→5.00 and rate 2600→3000');

insert into orders (id, user_id, variant_id, quantity, idempotency_key, fulfillment_data)
values ('20000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000001',
        '00000000-0000-4000-c000-000000000001', 1, gen_random_uuid(), '{"player_id":"123456"}');
select results_eq(
  $$ select unit_price_usd, usd_sdg_rate, total_sdg from orders
      where id = '20000000-0000-4000-8000-000000000003' $$,
  $$ values (5.00::numeric, 3000::numeric, 15000::numeric) $$,
  'a NEW order uses the new price and rate');

-- 3. The snapshot cannot be edited afterwards, by any role.
select throws_ok(
  $$ update orders set total_sdg = 1 where id = '20000000-0000-4000-8000-000000000001' $$,
  '42501', 'ORDER_SNAPSHOT_IMMUTABLE', 'total_sdg cannot be edited (as postgres)');
select throws_ok(
  $$ update orders set unit_price_usd = 0.01, total_usd = 0.03
      where id = '20000000-0000-4000-8000-000000000001' $$,
  '42501', 'ORDER_SNAPSHOT_IMMUTABLE', 'price columns cannot be edited');
select throws_ok(
  $$ update orders set usd_sdg_rate = 1 where id = '20000000-0000-4000-8000-000000000001' $$,
  '42501', 'ORDER_SNAPSHOT_IMMUTABLE', 'rate snapshot cannot be edited');
select throws_ok(
  $$ delete from orders where id = '20000000-0000-4000-8000-000000000001' $$,
  '42501', null, 'orders cannot be deleted');

-- 4. Invoice copies the order snapshot and is immutable too.
insert into payment_receipts (order_id, bank_account_id, transaction_ref, storage_path, file_sha256)
select '20000000-0000-4000-8000-000000000001', id, 'SNAP-001', 'p.jpg', repeat('a', 64)
  from bank_accounts order by sort_order limit 1;
update payment_receipts set status = 'accepted', reviewed_at = now()
 where order_id = '20000000-0000-4000-8000-000000000001';
update orders set status = 'processing' where id = '20000000-0000-4000-8000-000000000001';
update orders set status = 'completed' where id = '20000000-0000-4000-8000-000000000001';
-- Completion issued the invoice in the same transaction (Phase 8).
create temp table inv on commit drop as
  select id from invoices where order_id = '20000000-0000-4000-8000-000000000001';
select is((select count(*)::int from inv), 1, 'completing the order issued exactly one invoice');

select results_eq(
  $$ select total_usd, usd_sdg_rate, total_sdg,
            (snapshot -> 'order' ->> 'unit_price_usd')::numeric
       from invoices where id = (select id from inv) $$,
  $$ values (3.30::numeric, 2600::numeric, 8580::numeric, 1.10::numeric) $$,
  'invoice totals come from the order snapshot, not current prices or the caller');

update product_variants set price_usd = 9.99 where id = '00000000-0000-4000-c000-000000000001';
update app_settings set usd_sdg_rate = 4000 where id;
select results_eq(
  $$ select total_usd, usd_sdg_rate, total_sdg from invoices
      where id = (select id from inv) $$,
  $$ values (3.30::numeric, 2600::numeric, 8580::numeric) $$,
  'invoice unchanged after later price and rate changes');

select throws_ok(
  $$ update invoices set total_sdg = 1 where id = (select id from inv) $$,
  '42501', 'INVOICE_IMMUTABLE', 'invoice totals cannot be edited');
select throws_ok(
  $$ update invoices set snapshot = '{}' where id = (select id from inv) $$,
  '42501', 'INVOICE_IMMUTABLE', 'invoice snapshot cannot be edited');
select throws_ok(
  $$ delete from invoices where id = (select id from inv) $$,
  '42501', null, 'invoices cannot be deleted');
select throws_ok(
  $$ update invoices set status = 'void' where id = (select id from inv) $$,
  'P0001', 'VOID_REASON_REQUIRED', 'voiding requires a reason');
select lives_ok(
  $$ update invoices set status = 'void', void_reason = 'test'
      where id = (select id from inv) $$,
  'issued → void with a reason is the only permitted change');
select throws_ok(
  $$ update invoices set status = 'issued' where id = (select id from inv) $$,
  '42501', null, 'a void invoice cannot be re-issued');
select is((select total_sdg from invoices where id = (select id from inv)),
          8580::numeric, 'void invoice still carries the original totals');

-- A new invoice for the order: whatever the caller sends is overwritten.
insert into invoices (order_id, invoice_number, total_sdg, total_usd, usd_sdg_rate, snapshot, issued_by)
values ('20000000-0000-4000-8000-000000000001', 'INV-1999-99999', 1, 1, 1, '{}',
        '10000000-0000-4000-8000-000000000001');
select results_eq(
  $$ select total_usd, usd_sdg_rate, total_sdg, issued_by is null, invoice_number <> 'INV-1999-99999'
       from invoices where order_id = '20000000-0000-4000-8000-000000000001' and status = 'issued' $$,
  $$ values (3.30::numeric, 2600::numeric, 8580::numeric, true, true) $$,
  'number, totals and issuer come from the database, not the caller');

select * from finish();
rollback;
